# Generated by Django 5.1.6 on 2025-03-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ride',
            fields=[
                ('userId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('pickUp', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('complete', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('driverId', models.CharField(default=None, max_length=200, null=True)),
                ('expectedTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
